todoproject/todoapp/urls.py
from django.urls import path
from todoapp import views

app_name='todoapp'

urlpatterns = [
    path('',views.add,name='add'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.TaskListView.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailView.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.TaskUpdateView.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>',views.TaskDeleteView.as_view(),name='cbvdelete')

    # path('details',views.details,name='details')
]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=250)
    priority = models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return self.name

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from todoapp.form import TaskForm
from todoapp.models import Task
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView


# Create your views here.
class TaskListView(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task'


class TaskDetailView(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'


class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail',kwargs={'pk':self.object.id})

class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')

def add(request):
    task1 = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('task', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task = Task(name=name, priority=priority, date=date)
        task.save()
    return render(request, 'home.html', {'task': task1})


# def details(request):
#
#     return render(request,'details.html')
def delete(request, id):
    if request.method == 'POST':
        task = Task.objects.get(id=id)
        task.delete()
        return redirect('/')
    return render(request, 'delete.html')


def update(request, id):
    task = Task.objects.get(id=id)
    f1 = TaskForm(request.POST or None, instance=task)
    if f1.is_valid():
        f1.save()
        return redirect('/')
    return render(request, 'edit.html', {'f': f1, 'task': task})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content%}
{%endblock%}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{%block content%}
<form method="post">
  {% csrf_token %}
  are you sure to delete
  <input type="submit">
</form>
{% endblock %}

todoproject/templates/details.html
{% extends 'base.html' %}
{% block content %}
<div class=" shadow card">
    <div class="card-body">
        <h5 class="card-title">{{task.name}}</h5>
        <p><b>{{task.priority}}</b></p>
        <p><b>{{task.date}}</b></p>

        <a href="{% url 'todoapp:delete' task.id %}" class="btn btn-danger">DONE</a>
        <a href="{% url 'todoapp:update' task.id %}" class="btn btn-success">UPDATE</a>
    </div>
</div>
{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{f.as_p}}
    <button type="submit">Conform</button>
</form>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html'%}
{% block content%}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" id="exampleFormControlInput1" name="task"
                           placeholder="Enter Task">
                    <input type="text" class="form-control" name="priority" placeholder="Enter Priority">
                    <input type="date" class="form-control" name="date" placeholder="Enter Date">
                    <input type="submit" class="btn btn-success">
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <h4>Task to be completed</h4>
            {% for i in task %}
            <div class=" shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a href="{% url 'todoapp:delete' i.id%}" class="btn btn-danger">DONE</a>
                    <a href="{%url 'todoapp:update' i.id%}" class="btn btn-success">UPDATE</a>
                </div>
            </div>
            <br>
            {%endfor%}
        </div>
    </div>
</div>
{%endblock%}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update</div>
            <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}